import { Link, useLocation } from 'react-router-dom'
import { ArrowRight, Globe2, LockKeyhole, Radar, ShieldCheck, Wifi } from 'lucide-react'
import { ComingSoon } from '../components/States'
import { auth } from '../services/auth'
const cards=[['Wi-Fi Analyzer','Coming Soon',Wifi],['Internet Security Tests','Coming Soon',Globe2],['Website Security Analyzer','Coming Soon',LockKeyhole],['Security Score','Coming Soon',ShieldCheck]]
export function Dashboard(){const user=auth.get();return <div className="page"><p className="eyebrow">DASHBOARD · PHASE 1</p><h1>Welcome to <em>NetShield</em>{user?.guest?' · Guest':''}</h1><p className="page-lead">Your defensive security workspace is ready. Analysis modules will arrive in future phases.</p>{user?.guest&&<div className="guest-banner">Guest mode provides limited access. Create an account to save your analysis history and preferences. <Link to="/signup">Create account</Link></div>}<div className="dash-grid">{cards.map((item)=>{const [title,status,Icon]=item as [string,string,typeof Wifi];return <Link to="/wifi" className="dash-card" key={title}><div><Icon/><span>{status}</span></div><h3>{title}</h3><p>Foundation ready for a safe, transparent analysis experience.</p><ArrowRight size={17}/></Link>})}</div><section className="security-promise"><Radar/><div><h3>Built responsibly</h3><p>No live scans or security results are performed in Phase 1. NetShield is an educational project for authorized environments only.</p></div></section></div>}
const names:Record<string,string>={'/wifi':'Wi-Fi Analyzer','/internet':'Internet Security Tests','/website':'Website Security Analyzer','/checklist':'Security Checklist','/education':'Security Education'}
export function FuturePage(){const loc=useLocation();return <div className="page"><ComingSoon title={names[loc.pathname]||'Coming soon'} description="This module is part of NetShield’s roadmap. It will only provide defensive, permission-based checks."/></div>}
export function Settings(){return <div className="page"><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><div className="setting-card"><h3>Appearance</h3><p>Use the theme button in the navigation to switch between dark and light mode. Your preference is saved on this device.</p></div></div>}
export function About(){return <div className="page about"><p className="eyebrow">PROJECT INFORMATION</p><h1>About <em>NetShield</em></h1><p className="page-lead">NetShield is an educational cybersecurity project designed to help users understand the security of their own internet and Wi-Fi environment.</p><section className="about-grid"><article className="card"><h2>Project Created By</h2><p><strong>Harshal Santoshi</strong><br/>3rd Year Diploma Student<br/>Information Technology / Cybersecurity<br/>Government Polytechnic Murtizapur</p></article><article className="card"><h2>Project purpose</h2><p>NetShield provides a clear foundation for learning about defensive network security, with future tools designed to communicate results transparently.</p><p className="muted">Contact information will be added in a later phase.</p></article></section><section className="principles"><h2>Security &amp; privacy principles</h2><ul><li>Defensive and educational by design.</li><li>For networks and systems you own or have permission to test.</li><li>Does not crack Wi-Fi passwords, jam networks, or run deauthentication attacks.</li><li>Does not steal credentials or conduct unauthorized exploitation.</li></ul></section></div>}
