import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { Brand } from '../components/Brand'
import { ErrorMessage, SuccessNotification } from '../components/States'
import { auth } from '../services/auth'
const emailOK=(email:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}) {const [show,setShow]=useState(false);const password=type==='password';return <label className="field">{label}<span className="input-wrap"><input type={password&&!show?'password':type} value={value} onChange={e=>onChange(e.target.value)} required/>{password&&<button type="button" aria-label="Show password" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</span></label>}
export function Login(){const nav=useNavigate();const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [error,setError]=useState(''); const submit=(e:React.FormEvent)=>{e.preventDefault();if(!emailOK(email)||!pass)setError('Enter a valid email address and password.');else{auth.set({name:email.split('@')[0],email});nav('/dashboard')}};const guest=()=>{auth.set({name:'Guest',email:'',guest:true});nav('/dashboard')};return <AuthShell title="Welcome back" caption="Sign in to continue to your NetShield workspace."><form onSubmit={submit}>{error&&<ErrorMessage message={error}/>}<Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={pass} onChange={setPass} type="password"/><div className="form-row"><label><input type="checkbox"/> Remember me</label><a href="#reset">Forgot password?</a></div><button className="button full">Login</button><button className="button secondary full" type="button" onClick={guest}>Continue as Guest</button><p className="guest-note">Guest mode provides limited access. Create an account to save your analysis history and preferences.</p><p className="form-bottom">New to NetShield? <Link to="/signup">Create Account</Link></p></form></AuthShell>}
export function Signup(){const nav=useNavigate();const [name,setName]=useState('');const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const score=pass.length>=12&&/[A-Z]/.test(pass)&&/\d/.test(pass)?'Strong':pass.length>=8?'Fair':'Weak';const submit=(e:React.FormEvent)=>{e.preventDefault();if(name.trim().length<2)setError('Please enter your full name.');else if(!emailOK(email))setError('Please enter a valid email address.');else if(pass.length<8)setError('Use at least 8 characters for your password.');else if(pass!==confirm)setError('Passwords do not match.');else{auth.set({name:name.trim(),email});nav('/dashboard')}};return <AuthShell title="Create your account" caption="Start exploring your network with NetShield."><form onSubmit={submit}>{error&&<ErrorMessage message={error}/>}<Field label="Full Name" value={name} onChange={setName}/><Field label="Email" value={email} onChange={setEmail} type="email"/><Field label="Password" value={pass} onChange={setPass} type="password"/><div className="strength"><span>Password strength</span><b className={score.toLowerCase()}>{score}</b><i><em className={score.toLowerCase()}/></i></div><Field label="Confirm Password" value={confirm} onChange={setConfirm} type="password"/><button className="button full">Create Account</button><p className="form-bottom">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthShell>}
function AuthShell({title,caption,children}:{title:string;caption:string;children:React.ReactNode}){return <main className="auth-page"><header><Brand/><Link to="/">Back to home</Link></header><section className="auth-wrap"><aside><ShieldCheck/><p className="eyebrow">NETSHIELD ACCESS</p><h1>Your network. <em>More clarity.</em></h1><p>Educational tools for understanding the security of internet and Wi-Fi environments you own or have permission to test.</p></aside><article className="auth-card"><h2>{title}</h2><p>{caption}</p>{children}</article></section></main>}
